---

- name: Copy Nginx Repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Yum Nginx Packages
  yum: name=nginx state=installed

#- name: Copy Nginx Config
#  template: src=rancher.conf.j2 dest=/etc/nginx/conf.d/rancher.conf