---
- name: Copy the CentOS repository definition
  copy: src=CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo force=yes

- name: Copy the Docker repository definition
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo force=yes

- name: Create the repository for EPEL
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Firewalld service stop
  service:  name=firewalld  state=stopped  enabled=no

- name: Chronyd service stop
  service:  name=chronyd state=stopped  enabled=no

- name: Install Ansible Base package
  yum: name={{item}}  state=installed
  with_items:
    - libselinux-python
    - libsemanage-python
    - ntp

- name: Configure SELinux to disable
  selinux:  state=disabled

- name: Change TimeZone
  timezone:
    name: Asia/Shanghai

- name: Copy NTP conf
  copy: src=ntp.conf dest=/etc/ntp.conf force=yes

- name: NTP Start
  service: name=ntpd  state=started  enabled=yes