- hosts: docker

  roles:
  - common

- hosts: haproxy

  roles:
  - common

- hosts: docker

  roles:
  - docker
  - splash

  tags:
  - splash

- hosts: haproxy

  roles:
  - haproxy

  tags:
  - lb
