---
- name: Yum Install Zabbix Agent
  yum:
    name: zabbix-agent
    state: latest

- name: Create Zabbix Script directory
  file: path=/opt/zabbix/scripts state=directory owner=zabbix group=zabbix

- name: Copy Zabbix Script
  copy: src={{item}} dest=/opt/zabbix/scripts/{{item}} force=yes owner=zabbix group=zabbix mode=750
  with_items:
    - discovery_process.sh
    - process_check.sh

- name: Copy Zabbix Userparameter Script.conf
  copy: src=userparameter_script.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_script.conf force=yes

- name: Enable Zabbix Agent Sevices
  systemd: name=zabbix-agent state=started enabled=yes
